# Generated by Django 4.1.7 on 2023-06-07 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_report_bio'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
