# Generated by Django 4.1.7 on 2023-06-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_post_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
