# Generated by Django 4.1.7 on 2023-06-08 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_referencia_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyReferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verify_references', to='app.post')),
                ('references', models.ManyToManyField(blank=True, related_name='verify_references', to='app.referencia')),
            ],
            options={
                'db_table': 'verify_references',
            },
        ),
    ]
