# Generated by Django 4.1.7 on 2023-06-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_verifyreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencia',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
