# Generated by Django 4.1.7 on 2023-06-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_referencia_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyreferences',
            name='as_verified',
            field=models.BooleanField(default=False),
        ),
    ]
